#!/usr/bin/env python

from TODO import TODO  # remove when done

from docopt import docopt
from USAGE import USAGE, VERSION
from ProjectGenerator import ProjectGenerator
from ProjectTypesList import ProjectTypesList
from ConfigManager import ConfMgr


class App:

    def run(self):
        """!
        entrypoint to the application
        """
        args = docopt(USAGE, version=VERSION)
        self.__initConfig(args)

    def __initConfig(self, args: dict):
        """!
        parses the specified config file if one is provided; otherwise it
        defaults to the basic behaviour of the confMgr class.
        """
        cfg = ConfMgr()
        cfg.parse(args)
